asterisk -rx 'database put WESTILLFAX step 00'

asterisk -rx 'database put WESTILLFAX/call_time 00 145'
asterisk -rx 'database put WESTILLFAX/call_time 01 80'
asterisk -rx 'database put WESTILLFAX/call_time 04 35'
asterisk -rx 'database put WESTILLFAX/call_time 05 150'
asterisk -rx 'database put WESTILLFAX/call_time 07 70'
asterisk -rx 'database put WESTILLFAX/call_time 09 90'
asterisk -rx 'database put WESTILLFAX/call_time 11 45'
asterisk -rx 'database put WESTILLFAX/call_time 13 75'
asterisk -rx 'database put WESTILLFAX/call_time 15 80'
asterisk -rx 'database put WESTILLFAX/call_time 17 145'
asterisk -rx 'database put WESTILLFAX/call_time 19 90'
asterisk -rx 'database put WESTILLFAX/call_time 20 65'
asterisk -rx 'database put WESTILLFAX/call_time 21 76'
asterisk -rx 'database put WESTILLFAX/call_time 22 60'
asterisk -rx 'database put WESTILLFAX/call_time 23 150'
asterisk -rx 'database put WESTILLFAX/call_time 25 45'
asterisk -rx 'database put WESTILLFAX/call_time 27 55'
asterisk -rx 'database put WESTILLFAX/call_time 29 77'

asterisk -rx 'database put WESTILLFAX/wait_time 00 40'