[hello]
exten=>hello,1,Verbose(1, hello world call)
same=>n,Playback(/fax/sounds/fax/00)
same=>n,Hangup()

exten=>infinitescroll,1,Verbose(1, inf scroll call)
same => n,SendFax(/fax/tifs/nua/guesswhofrompptx.tif)
;same => n,SendFax(/fax/tifs/tester.tif)
same=>n,Hangup()

;TESTER
[tester]
exten =>tester,1,Verbose(1, tester call)
same => n,SendFax(/fax/tifs/tester.tif)
same => n,Hangup()